name: Hub Target Data Validation (R)

on:
  workflow_dispatch:
  pull_request:
    branches: [main, main-target-dir-v5]
    paths:
      - 'target-data/time-series.*'
      - 'target-data/time-series/**'
      - 'target-data/oracle-output.*'
      - 'target-data/oracle-output/**'
    paths-ignore:
      - '**/README'
      - '**/README.*'
      - '**/readme'
      - '**/readme.*'

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-target-data:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: Update R
        run: |
          sudo apt-get update

      # Install dependencies, but skip hubValidations here
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::sessioninfo

      # Install dev version of hubValidations from GitHub branch
      - name: Install dev hubValidations
        run: |
          Rscript -e 'remotes::install_github("hubverse-org/hubValidations@ak/validate-target-pr/264")'

      - name: Run target data validations
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          library("hubValidations")
          v <- hubValidations::validate_target_pr(
              gh_repo = Sys.getenv("GITHUB_REPOSITORY"),
              pr_number = Sys.getenv("PR_NUMBER")
          )
          hubValidations::check_for_errors(v, verbose = TRUE)
        shell: Rscript {0}
